augmenter:
  factor: 1
  do_vshift: true
  do_smear: true
  smear_radius: 3
  smear_filter: "max"
  do_noise: true
  noise_factor: 0.05
encoder:
  kernel_size: 3
  padding: 1
  stride: 1
  channel_size: 8
  pool_size: 2
  activation: "silu"
decoder:
  padding: 0
  stride: 2
  channel_size: 8
  out_dim2: 1
  activation: "silu"
model_name: "bad autoencoder"
trainer:
  loss: "mse"
  epochs: 10
  log_dir: "runs"
  log_tag: "pythonize"
  noise_factor: 0.05
  learning_rate: 0.001
loader:
  batch_size: 32
  shuffle: true
  num_workers: 4
  overfit: false
  overfit_index: 0
  overfit_amount: 3200
modules:
- "printer"
- "augmenter"
- "loader"
- "model"
- "trainer"

